# this is written by the kcm-o, but we initialize here to cleanly handle the adoption case
apiVersion: v1
kind: ConfigMap
metadata:
  name: csr-controller-ca
  namespace: openshift-config-managed
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDHjCCAgagAwIBAgIIeuLxgzewWr0wDQYJKoZIhvcNAQELBQAwLTESMBAGA1UE
    CxMJb3BlbnNoaWZ0MRcwFQYDVQQDEw5rdWJlbGV0LXNpZ25lcjAeFw0xOTEwMDEy
    MzAzMTZaFw0xOTEwMDIyMzAzMTZaMC0xEjAQBgNVBAsTCW9wZW5zaGlmdDEXMBUG
    A1UEAxMOa3ViZWxldC1zaWduZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQChPTEO+gfL5nD11T6JwThgisXNrd7Z8pNFfjdAs52zmGPGPONtL27NiT+C
    9K/1HrUp9BRtzf2xrsFAsUazXz8/uCJWZzYqMg+PgYtYBwoe6ba9AHnVxPiz4DGs
    HlHLhUlkmIStJuLyzlZ+SuPAYed7Zy7gcQzAuxO6IdPv+5RuXQibeXw/1poFwuFg
    z4eAxaVV4qnKZtjxj9ks2Viqc02ggxI/gSp1cfJt9QaCD+HqhvEiEZPVG6oNPCfc
    CKPLB7CRTN1CymjErFdr8z59rqODyH+ZPFLuKB5c+ETZtIF9QJ9meBdLp6KTJWph
    6DiTfzXj7FWxw+0pjZ3SqFYIjOEJAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICpDAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSKX57gmFJymxcltf/O1mbjAGw2GzAN
    BgkqhkiG9w0BAQsFAAOCAQEAfBYqM3UbjE8O8L5+B1OqvHTF7EplBdnyyZx9Zib/
    PcU9mFJuo6FOLzSh/N5JyLNyREeDkpWfzkZTx1/ExW5iqXOpgw+DWBwJnZtLpThA
    smeHqDzKEtIfk9yjv0MBdZmtIen+wQkfmL+bBgbQ6i1PMaWi4cKnRB1HlrnKUEmB
    nGBL6xcnwrVQXXzQMvLDJ8yopwv1jIphWK6L4hAaO68hpK6ElKPtNjbILJdxBbF6
    QnOhWMy3rdoDxbahalmFOHh5JtS8VSzsroIMrj/efDIJsQU03P2QNHlpdGdYaC73
    +Wua/WipiXif9sdCQ8HPX1zq2h66r8ujoTjDBfDNKH3cHg==
    -----END CERTIFICATE-----
    

