apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  creationTimestamp: null
  name: image-policy-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - registry.local:5000/ocp4/openshift4
    source: quay.io/openshift-release-dev/ocp-release-nightly
